import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting database seed...');








































































































  });    await prisma.$disconnect();  .finally(async () => {  })    process.exit(1);    console.error('💥 Error seeding database:', e);  .catch((e) => {main()}  console.log('🎉 Database seed completed successfully!');  console.log(`✅ Created transactions: ${transaction1.id}, ${transaction2.id}`);  });    },      status: 'completed',      merchantName: 'Employer Inc',      category: 'Income',      description: 'Salary deposit',      type: 'credit',      amount: 1000.00,      accountId: checkingAccount.id,    data: {  const transaction2 = await prisma.transaction.create({  });    },      status: 'completed',      merchantCategory: 'Cafe',      merchantName: 'Starbucks',      category: 'Food & Drink',      description: 'Coffee shop purchase',      type: 'debit',      amount: 50.00,      cardId: debitCard.id,      accountId: checkingAccount.id,    data: {  const transaction1 = await prisma.transaction.create({  // Create test transactions  console.log(`✅ Created card: ${debitCard.cardNumber}`);  });    },      dailyLimit: 500.00,      isFrozen: false,      isActive: true,      cardType: 'debit',      expiry: new Date('2026-12-31'),      cvv: '123',      cardNumber: '4532-1111-1111-1111', // Visa test number      accountId: checkingAccount.id,    create: {    update: {},    where: { cardNumber: '4532-1111-1111-1111' },  const debitCard = await prisma.card.upsert({  // Create test cards  console.log(`✅ Created accounts: ${checkingAccount.accountNumber}, ${savingsAccount.accountNumber}`);  });    },      isActive: true,      currency: 'USD',      balance: 10000.00,      accountNumber: 'ACC-001-SAV',      accountType: 'savings',      userId: user.id,    create: {    update: {},    where: { accountNumber: 'ACC-001-SAV' },  const savingsAccount = await prisma.account.upsert({  });    },      isActive: true,      currency: 'USD',      balance: 5000.00,      accountNumber: 'ACC-001-CHK',      accountType: 'checking',      userId: user.id,    create: {    update: {},    where: { accountNumber: 'ACC-001-CHK' },  const checkingAccount = await prisma.account.upsert({  // Create test accounts  console.log(`✅ Created user: ${user.email}`);  });    },      lastName: 'Doe',      firstName: 'John',      password: hashedPassword,      email: 'john@example.com',    create: {    update: {},    where: { email: 'john@example.com' },  const user = await prisma.user.upsert({    const hashedPassword = await bcrypt.hash('password123', 10);n  // Create test user